// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTbGYrZluLbFEFVj8OSSA9To8YEt8qEKY',
    appId: '1:19596451195:web:2c451b0d8fb812bb23b1de',
    messagingSenderId: '19596451195',
    projectId: 'appchat-6a1eb',
    authDomain: 'appchat-6a1eb.firebaseapp.com',
    storageBucket: 'appchat-6a1eb.appspot.com',
    measurementId: 'G-H8EZSPKHKJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDySR4lOp3UJCd-pwFTyvEOseGrE3e4yYo',
    appId: '1:19596451195:android:c1334ece07049a7023b1de',
    messagingSenderId: '19596451195',
    projectId: 'appchat-6a1eb',
    storageBucket: 'appchat-6a1eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuOToyvSpR32J3AE5de2CUZq6XYAYVFnM',
    appId: '1:19596451195:ios:98450d1b996c2d3123b1de',
    messagingSenderId: '19596451195',
    projectId: 'appchat-6a1eb',
    storageBucket: 'appchat-6a1eb.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuOToyvSpR32J3AE5de2CUZq6XYAYVFnM',
    appId: '1:19596451195:ios:d402d3e3a1692af023b1de',
    messagingSenderId: '19596451195',
    projectId: 'appchat-6a1eb',
    storageBucket: 'appchat-6a1eb.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
