// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYQtBy_lFUoJ5OX_7lJhT90l9oC6hUsDM',
    appId: '1:440133166353:web:ad4835841507abf2ea58b0',
    messagingSenderId: '440133166353',
    projectId: 'mychat-d1267',
    authDomain: 'mychat-d1267.firebaseapp.com',
    storageBucket: 'mychat-d1267.appspot.com',
    measurementId: 'G-8NW558D7VD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzDWu3nLxayc3nbYepUJBXu3s2_wu3jn0',
    appId: '1:440133166353:android:a15766b5fce8dce2ea58b0',
    messagingSenderId: '440133166353',
    projectId: 'mychat-d1267',
    storageBucket: 'mychat-d1267.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1EEvRlEuS_eAzGKqj4glyx6tw3zR2qJ4',
    appId: '1:440133166353:ios:6efe6aae143d223dea58b0',
    messagingSenderId: '440133166353',
    projectId: 'mychat-d1267',
    storageBucket: 'mychat-d1267.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1EEvRlEuS_eAzGKqj4glyx6tw3zR2qJ4',
    appId: '1:440133166353:ios:62e5624958868f9cea58b0',
    messagingSenderId: '440133166353',
    projectId: 'mychat-d1267',
    storageBucket: 'mychat-d1267.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
